# NumPy biblioteka

**NumPy** je Python biblioteka koja podržava rad sa višedimenzionalnim nizovima, kao i brojnim matematičkim operacijama koje se mogu primeniti nad njima. Na [ovom](http://www.numpy.org/) linku se nalazi zvanična stranica biblioteke, a [ovde](https://docs.scipy.org/doc/numpy/user/quickstart.html) se može pronaći koristan tutorijal.

In [1]:
import numpy as np

Sledeći zadaci ilustruju neke od mogućnosti NumPy bibloteke.

**1.** Kreirati niz $a$ od 3 elementa i matricu $M$ dimenzija $2 \times 3$ čiji su elementi tipa `float32`. Ispisati oblik, veličinu, broj dimenzija i tip elemenata niza $a$, odnosno matrice $M$.

In [2]:
a = np.array([1, 2, 3])
M = np.array([[1, 2, 3], [4, 5, 6]], dtype='float32')

print('Niz a:')
print(a)
print('shape =', a.shape)
print('size =', a.size)
print('ndim =', a.ndim)
print('dtype =', a.dtype, end='\n\n')

print('Matrica M:')
print(M)
print('shape =', M.shape)
print('size =', M.size)
print('ndim =', M.ndim)
print('dtype =', M.dtype)

Niz a:
[1 2 3]
shape = (3,)
size = 3
ndim = 1
dtype = int64

Matrica M:
[[1. 2. 3.]
 [4. 5. 6.]]
shape = (2, 3)
size = 6
ndim = 2
dtype = float32


NumPy paket podržava podrazumevane tipove kao što su `int_`, `float_`, `bool_` i `complex_`, ali nudi mogućnost i rada sa tipovima drugačijih opsega i preciznosti poput `int8`, `int16`, `uint8`, `float32`, `float64`, `complex128`, i slično.

**2.** Generisati nizove i matrice na sledeći način:

* Niz $a_1$ tako što se zadaju početna i krajnja tačka sa odgovarajućim korakom.
* Niz $a_2$ gde se zadaju početna i krajnja tačka i broj ekvidistantnih elemenata u datom intervalu.
* Niz $a_3$ koji se sastoji samo od nula.
* Niz $a_4$ koji sadrži brojeve iz uniformne raspodele [0, 1).
* Matricu $M_1$ koja se sastoji samo od jedinica.
* Jediničnu matricu $M_2$ dimenzije 3.
* Dijagonalnu matricu $M_3$ na čijoj se glavnoj dijagonali nalaze redom brojevi 4, 3, 2 i 1.
* Matricu $M_4$ čiji su elementi iz standardne normalne raspodele.

In [3]:
a1 = np.arange(1, 10, 2)
a2 = np.linspace(1, 3, 21)
a3 = np.zeros(6)
a4 = np.random.uniform(2, 5, 5)

print('a1 =', a1)
print('a2 =', a2)
print('a3 =', a3)
print('a4 =', a4)

M1 = np.ones((2, 3))
M2 = np.eye(3)
M3 = np.diag([4, 3, 2, 1])
M4 = np.random.randn(4, 3)

print('M1 =\n', M1)
print('M2 =\n', M2)
print('M3 =\n', M3)
print('M4 =\n', M4)

a1 = [1 3 5 7 9]
a2 = [1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7
 2.8 2.9 3. ]
a3 = [0. 0. 0. 0. 0. 0.]
a4 = [3.00524236 2.9109637  4.30078812 2.81802691 2.81601515]
M1 =
 [[1. 1. 1.]
 [1. 1. 1.]]
M2 =
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
M3 =
 [[4 0 0 0]
 [0 3 0 0]
 [0 0 2 0]
 [0 0 0 1]]
M4 =
 [[-0.1165821  -0.1607829  -0.59030684]
 [ 0.09299698  1.14606227 -1.13026953]
 [-0.25682517  2.44852086  0.49175988]
 [ 0.69238257  0.26537287  0.31595618]]


Funkcija `np.random.randn(...)` vraća proizvoljnu vrednost iz standardne normalne raspodele $N(0, 1)$. Za generisanje proizvoljne vrednosti iz normalne raspodele $N(\mu, \sigma^2)$ može se koristiti izraz `sigma * np.random.randn(...) + mu` ili funkcija `np.random.normal(...)` sa parametrima $\mu$ i $\sigma$.

**3.** Date su matrice $M_1=\begin{bmatrix}1&3&5\\7&9&11\\13&15&17\end{bmatrix}$ i $M_2=\begin{bmatrix}2&4&6\\8&10&12\\14&16&18\end{bmatrix}$. Odrediti vrednosti sledećih matrica:

* $M_1 + M_2$, gde operacija $+$ označava sabiranje po koordinatama;
* $M_1 \cdot M_2$, gde operacija $\cdot$ označava sabiranje po koordinatama;
* $M_1 \times M_2$, gde operacija $\times$ označava matrično množenje;
* transponovanu matricu $M_1^T$ matrice $M_1$;
* $\sin (M_1)$, gde se vrednost funkcije $\sin x$ računa po koordinatama;
* $\exp (M_2)$, gde se vrednost funkcije $e^x$ računa po koordinatama.

In [4]:
M1 = np.array([[1, 3, 5], [7, 9, 11], [13, 15, 17]])
M2 = np.array([[2, 4, 6], [8, 10, 12], [14, 16, 18]])
print('M1 + M2 =\n', M1 + M2)
print('M1 * M2 =\n', M1 * M2)
print('M1 x M2 =\n', M1.dot(M2), '=\n', np.dot(M1, M2))
print('transpose(M1) =\n', M1.T, '=\n', M1.transpose())
print('sin(M1) =\n', np.sin(M1))
print('exp(M2) =\n', np.exp(M2))

M1 + M2 =
 [[ 3  7 11]
 [15 19 23]
 [27 31 35]]
M1 * M2 =
 [[  2  12  30]
 [ 56  90 132]
 [182 240 306]]
M1 x M2 =
 [[ 96 114 132]
 [240 294 348]
 [384 474 564]] =
 [[ 96 114 132]
 [240 294 348]
 [384 474 564]]
transpose(M1) =
 [[ 1  7 13]
 [ 3  9 15]
 [ 5 11 17]] =
 [[ 1  7 13]
 [ 3  9 15]
 [ 5 11 17]]
sin(M1) =
 [[ 0.84147098  0.14112001 -0.95892427]
 [ 0.6569866   0.41211849 -0.99999021]
 [ 0.42016704  0.65028784 -0.96139749]]
exp(M2) =
 [[7.38905610e+00 5.45981500e+01 4.03428793e+02]
 [2.98095799e+03 2.20264658e+04 1.62754791e+05]
 [1.20260428e+06 8.88611052e+06 6.56599691e+07]]


**4.** Dati su nizovi $x = [1, 2, 3]$ i $y = [5, 6, 7]$. 

* Nadovezati ih po vertikali i po horizontali.
* Odrediti njihov skalarni proizvod.
* Odrediti maksimalni element niza *x*.
* Odrediti minimalni element niza *y*.
* Odrediti sve elemente niza *x* koji su veći od 1.5.

In [5]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
# vertikalno nadovezivanje
print(np.vstack((x, y)))
# horiznotalno nadovezivanje
print(np.hstack((x, y)))
# skalarni proizvod
print(np.sum(x * y))
# minimalni element niza x
print(np.min(x))
# maksimalni element niza y
print(y.max())
#elementi niza x koji su veci od 1.5
print(x[x > 1.5])

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
32
1
6
[2 3]


**5.** Date su matrice $A=\begin{bmatrix}1&2&3\\4&5&6\end{bmatrix}$ i $B=\begin{bmatrix}1&2&3\\4&6&6\end{bmatrix}$. 

* Proveriti da li su matrice jednake.
* Proveriti da li su matrice jednake po svakoj koordinati.
* Izvršiti preraspodelu elemenata matrice *A* tako da se dobije matrica $3 \times 2$.
* Izvršiti sravnjivanje elemenata matrice *A* tj. svodjenje matrice na niz.
* Odrediti sumu elemenata matrice *B* koji su jednaki 6.

In [6]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 2, 3], [4, 6, 6]])

# jendakost dve matrice
print(np.array_equal(A, B))

# jednakost po koordinatama
print(A == B)

# matrica 3x2 od matrice 2x3
print(A.reshape(3, 2))

# sravnjivanje elemenata
print(A.flatten())

# suma elemenata koji su jednaki 6
print(np.sum(B[B == 6]))

False
[[ True  True  True]
 [ True False  True]]
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
12


**6.** Za $M = \begin{bmatrix}1&2&3\\4&5&6\end{bmatrix}$ i $x = [10, 20, 30]$ izračunati vrednosti $2M$, $x-3$ i $M+x$. 

In [7]:
M = np.array([[1, 2, 3], [4, 5, 6]])
x = np.array([10, 20, 30])
print(2*M)
print(x - 3)
print(M + x)

[[ 2  4  6]
 [ 8 10 12]]
[ 7 17 27]
[[11 22 33]
 [14 25 36]]


Prethodni slučajevi ukazuju na izvršavanje računskih operacija između struktura koje su različitih dimenzija. Moguće je sabirati niz ili matricu sa skalarom tako što se izvrši sabiranje po svakoj koordinati ili izvršavati sabiranje matrice dimenzije $p \times q$ i niza od $q$ elemenata. Ova pojava se u Python jeziku naziva *broadcasting* i može se uopštiti i na slučajeve sa više dimenzija. O njoj treba voditi računa jer se neke greške u pogledu neusaglašenosti dimenzija mogu teže otkriti. 

**7.** Odrediti sumu onih elemenata matrice koji su veći od njenog prosečnog elementa.

In [8]:
M = np.arange(9).reshape(3, 3)
print('M =\n', M)
average = np.average(M)
print(np.sum(M[M > average]))

M =
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
26


Prosečna vrednost u matrici je 4, pa je $5 + 6 + 7 + 8 = 26$.

**8.** Konstruisati matricu koja na sporednoj dijagonali ima redom elemente 4, 3, 2 i 1, a na osalim pozicijama nule.

In [9]:
n = 4
M = np.zeros((n, n))
for i in range(n):
    M[n-1-i,i] = i + 1
print(M)

[[0. 0. 0. 4.]
 [0. 0. 3. 0.]
 [0. 2. 0. 0.]
 [1. 0. 0. 0.]]


**9.**

Neka je $M = \begin{bmatrix}1&2&3&4\\5&6&7&8\\9&10&11&12\end{bmatrix}$. U nastavku su dati neki primeri ispisa elemenata matrice $M$ (enumeracija počinje od 0):

In [10]:
M = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [11]:
print('Pojedinacni element:', M[1,2])
print('Prva vrsta:', M[1])
print('Nulta kolona:', M[:,0])
print('Svaki drugi element poslednje kolone:', M[::2, -1])

Pojedinacni element: 7
Prva vrsta: [5 6 7 8]
Nulta kolona: [1 5 9]
Svaki drugi element poslednje kolone: [ 4 12]


In [12]:
# pozicije se generisu na osnovu prvih i drugih koordinata
print('Elementi na pozicijama (1,2) i (1,3):', M[(1,1), (2,3)])

Elementi na pozicijama (1,2) i (1,3): [7 8]


Neka je $M = \begin{bmatrix}1&2&3&4&5\\6&7&8&9&10\\11&12&13&14&15\\16&17&18&19&20\\21&22&23&24&25\end{bmatrix}$. U nastavku su dati neki primeri ispisa elemenata matrice $M$:

In [13]:
M = np.arange(25).reshape(5, 5) + 1

In [14]:
print('Vrednosti od 3. do 4. elementa u nultom redu:', M[0,3:5])
print('Kvadratna podmatrica reda 2 u donjem desnom uglu:\n', M[-2:,-2:])
print('Elementi svakog drugog reda pocev od 2. i elementi svake druge kolone:\n', M[2::2,::2])
print('Elementi sa koordinatama (0,2), (1,3), (2,4):', M[(0,1,2),(2,3,4)])

Vrednosti od 3. do 4. elementa u nultom redu: [4 5]
Kvadratna podmatrica reda 2 u donjem desnom uglu:
 [[19 20]
 [24 25]]
Elementi svakog drugog reda pocev od 2. i elementi svake druge kolone:
 [[11 13 15]
 [21 23 25]]
Elementi sa koordinatama (0,2), (1,3), (2,4): [ 3  9 15]
