# Zadaci: linearna algebra

In [39]:
import numpy as np 
from numpy import linalg as LA 
import math

1) Odrediti sopstvene vrednosti i sopstvene vektore matrice 
$\begin{bmatrix}
    8 & 3 \\
    2 & 7   
\end{bmatrix} $.


In [12]:
A = np.array([[8, 3], [2, 7]])
A

array([[8, 3],
       [2, 7]])

In [3]:
values, vectors = LA.eig(A)

In [4]:
values

array([10.,  5.])

In [5]:
vectors

array([[ 0.83205029, -0.70710678],
       [ 0.5547002 ,  0.70710678]])

In [7]:
l1 = values[0]
l1

10.0

In [8]:
v1 = vectors[:, 0]
v1

array([0.83205029, 0.5547002 ])

In [9]:
np.dot(A, v1)

array([8.32050294, 5.54700196])

In [10]:
l1 * v1

array([8.32050294, 5.54700196])

2) Napisati funkciju koja proverava da li matrica zadovoljava Silvestrov kriterijum.

In [20]:
# Silvester
def silvester(A):
    assert A.ndim == 2, 'Fatal Error: invalid dims.'
    assert A.shape[0] == A.shape[1], 'Fatal Error: invalid shape.'
    n = A.shape[0]
    for i in range(1, n+1):
        tmp_A = A[:i, :i]
        if np.linalg.det(tmp_A) <= 0:
            return False
    return True

In [24]:
A = np.array([[1, 0, 0], [0, 3, 0], [0, 0, 5]])
A

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

In [25]:
silvester(A)

True

3) Napisati funkciju koja proverava da li je zadata realna kvadratna matrica dimenzije $n$ dijagonalno dominantna. 

Zatim, proveriti da li je matrica 
$\begin{bmatrix}
-4 & 2 & 1 \\
1 & 6 & 2 \\
1 & -2 & 5    
\end{bmatrix} $
dijagonalno dominantna.

Da li je matrica
$\begin{bmatrix}
3 & -2 & 1 \\
1 & -3 & 2 \\
-1 & 2 & 4    
\end{bmatrix} $ dijagonalno dominantna?

In [32]:
def diag_dom(A):
    assert A.ndim == 2, 'Fatal Error: invalid dims.'
    assert A.shape[0] == A.shape[1], 'Fatal Error: invalid shape.'
    n = A.shape[0]
    for i in range(n):
        if 2*abs(A[i,i]) <= sum(map(lambda t: abs(t), A[i,:])):
            return False
    return True

In [35]:
A = np.array([[-4, 20, 1], [1, 6, 2], [1, -2, 5]])
A

array([[-4, 20,  1],
       [ 1,  6,  2],
       [ 1, -2,  5]])

In [36]:
diag_dom(A)

False

In [ ]:
# |aii| > sum{j!=i}|aij|
# 2*|aii| > sum{j in 1..n}|aij|

In [38]:
v = np.array([-4, 20, 1])
list(map(lambda t: abs(t), v))

[4, 20, 1]

4) Normirati vektor (4, 1, -2, 2) u odnosu na $l_2$ normu. 


In [40]:
def l2(v):
    assert v.ndim == 1, 'Fatal Error: invalid size.'
    return math.sqrt(sum(map(lambda t: t**2,v)))

In [41]:
v = np.array([4, 1, -2, 2])
v

array([ 4,  1, -2,  2])

In [42]:
l2(v)

5.0

In [44]:
v_nrm = v / l2(v)
v_nrm

array([ 0.8,  0.2, -0.4,  0.4])

5)  

Pokazati da je sa $$(x_1, x_2, x_3) * (y_1, y_2, y_3) = x_1y_1 + x_2y_2 + x_3y_3$$  definisan skalarni proizvod u $R^3$. 
Izracunati potom skalarni prozivod vektora (2, 3, 1) i (8, 9, 12) kao i ugao izmedju njih. 


In [ ]:
# <a, b> = <b, a>
# <a,b> = (a1, a2, a3) * (b1, b2, b3) = a1b1 + a2b2 + a3b3 = b1a1 + b2a2 + b3a3 = (b1, b2, b3)*(a1,a2,a3) = <b,a>

In [ ]:
# <a, b + c> = <a, b> + <a, c>
# <a, alpha b> = alpha <a, b>

In [ ]:
# <a, a> = (a1, a2, a3) * (a1, a2, a3) = a1**2 + a2**2 + a3**2

In [45]:
def sp(v1, v2):
    assert v1.ndim == v2.ndim == 1, 'Fatal Error: invalid ndim.'
    assert v1.shape == v2.shape, 'Fatal Error: invalid shape.'
    return sum(v1*v2)

In [46]:
v1, v2 = np.array([2, 3, 1]), np.array([8, 9, 12])
v1, v2

(array([2, 3, 1]), array([ 8,  9, 12]))

In [47]:
sp(v1, v2)

55

In [50]:
sp(v1, v2) / ((math.sqrt(sp(v1, v1)))*(math.sqrt(sp(v2, v2))))

0.8646687238343141

In [51]:
math.acos(0.86)

0.5355266543143878

6) Napisati funkciju koja racuna vrednost linearnog kernela u prostoru $R^3$.

In [62]:
def k_lin(x, y, c):
    return sum(x.T * y) + c

In [63]:
x, y = np.array([1, 2, 3]), np.array([4, 2, 2])
x, y

(array([1, 2, 3]), array([4, 2, 2]))

In [64]:
k_lin(x, y, 10)

24

7) Izracunati vrednost Gausovog kernela za vektore (1, 3, 2) i (1, 1, 0). Za vrednost parametra sigma uzeti 0.5.

In [66]:
def k_gauss(x, y, sigma):
    assert x.shape==y.shape, 'Fatal Error: invalid dim.'
    return math.exp(-sum((x-y)**2)/(2*(sigma**2)))

In [67]:
x1, x2 = np.array([1, 3, 2]), np.array([1, 1, 0])

In [69]:
x1, x2

(array([1, 3, 2]), array([1, 1, 0]))

In [70]:
k_gauss(x1, x2, 0.5)

1.1253517471925912e-07

In [73]:
np.array([[3, 3], [0, 1]])

array([[3, 3],
       [0, 1]])